### ISSUE TITLE
how to keep container running

### ISSUE THREAD

**Issue by juan11perez** [r00tat/grive2#1]
Thank you for sharing this container. 
I got the initial sync done. 
I can then do subsequent syncs by typing this in the command line docker run --rm -it -v $(pwd):/drive paulwoelfel/grive2

but how do you keep the service running? If I try to set it up in docker compose the container keeps crashing.

thank you.

**Comment by r00tat** [comment]
Grive2 doesn't support continuous sync:

https://github.com/vitalif/grive2/blob/master/README.md

There are a few things that Grive does not do at the moment:

continously wait for changes in file system or in Google Drive to occur and upload. A sync is only performed when you run Grive (there are workarounds for almost continuous sync. See below).

**Comment by r00tat** [comment]
You could use a start script like `bash -c "while [[ true ]]; do grive; sleep 60; done"`
